-- Active: 1730295332111@@127.0.0.1@3306


USE est_caso_ii;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
    CPF_PASSAGEIRO INT PRIMARY KEY,
    NOME_PASSAGEIRO VARCHAR (100) NOT NULL,
    TEL_PASSAGEIRO VARCHAR (13) NOT NULL,
    RUA_PASSAGEIRO VARCHAR (100) NOT NULL,
    BAIRRO_PASSAGEIRO VARCHAR (50) NOT NULL,
    CIDADE_PASSAGEIRO VARCHAR (100) NOT NULL,
    NUMRESI_PASSAGEIRO INT NOT NULL,
    UF_PASSAGEIRO CHAR (2) NOT NULL,
    PAIS_PASSAGEIRO VARCHAR (50) NOT NULL
    );

ALTER TABLE PASSAGEIROS ADD COLUMN EMAIL_PASSAGEIRO VARCHAR(50);


CREATE TABLE IF NOT EXISTS VOOS(
    ID_VOOS INT PRIMARY KEY,
    DATA_ORIGEM DATE NOT NULL,
    HORA_ORIGEM TIME NOT NULL,
    PAIS_DESTINO VARCHAR (50) NOT NULL,
    PAIS_CHEGADA VARCHAR (50) NOT NULL,
    DATA_DESTINO DATE NOT NULL,
    HORA_DESTINO TIME NOT NULL,
    NOME_AEROPORT_ORIGEM VARCHAR (100) NOT NULL,
    NOME_AEROPORT_DESTINO VARCHAR (100) NOT NULL,
    ID_AERONAVE VARCHAR (10) NOT NULL,
    ID_AEROPORTO VARCHAR (10) NOT NULL,
    NUM_PASSAGEIROS_VOO INT NOT NULL
);

ALTER TABLE VOOS ADD PAIS_DESTINO VARCHAR(100);

CREATE TABLE IF NOT EXISTS AERONAVES(
    ID_AERONAVE INT PRIMARY KEY,
    NOME_AERONAVE VARCHAR (50) NOT NULL,
    NOME_PILOTO VARCHAR (100) NOT NULL,
    CAPACIDADE_AERONAVE INT NOT NULL,
    FABRICANTE_AERONAVE VARCHAR (100) NOT NULL,
    ANOFABRI_AERONAVE INT (4) NOT NULL,
    DATA_SAIDA_AERONAVE DATE NOT NULL,
    HORA_SAIDA_AERONAVE TIME NOT NULL,
    NUM_VOOS_AERONAVE INT NOT NULL,
    ID_VOOS INT
);

ALTER TABLE AERONAVES ADD FABRICANTE_AERONAVE VARCHAR(30);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
    ID_AEROPORTO INT PRIMARY KEY,
    NOME_AEROPORTO VARCHAR (100) NOT NULL,
    LOCAL_AEROPORTO VARCHAR (50) NOT NULL,
    PAIS_AEROPORTO VARCHAR (20) NOT NULL,
    LATITUDE_AEROPORTO VARCHAR (45) NOT NULL,
    LONGITUDE_AEROPORTO VARCHAR (45) NOT NULL,
    NUM_VOOS_AEROPORTO VARCHAR (45) NOT NULL,
    DATA_ENTRADA_AEROPORTO DATE NOT NULL,
    HORA_ENTRADA_AEROPORTO TIME NOT NULL,
    DATA_SAIDA_AEROPORTO DATE NOT NULL,
    HORA_SAIDA_AEROPORTO TIME NOT NULL,
    ID_VOOS INT NOT NULL
);

ALTER TABLE AEROPORTO MODIFY LONGITUDE_AEROPORTO INT;
ALTER TABLE AEROPORTO MODIFY LATITUDE_AEROPORTO INT;

CREATE TABLE IF NOT EXISTS RESERVAS(
    RESERVA_PASS INT,
    VOO_RESERVA_PASS INT,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY (RESERVA_PASS) REFERENCES PASSAGEIROS(CPF_PASSAGEIRO),
    CONSTRAINT FK_VOOS FOREIGN KEY (VOO_RESERVA_PASS) REFERENCES VOOS(ID_VOOS)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
    ID_FUNC INT PRIMARY KEY,
    FUNCAO_FUNC VARCHAR(30) NOT NULL,
    NOME_FUNC VARCHAR(50) NOT NULL,
    DATANASC_FUNC DATE NOT NULL,
    TELEFONE_FUNC VARCHAR(30) NOT NULL
);


CREATE TABLE IF NOT EXISTS EQUIPES(
    FUNC_EQUIPE INT,
    VOO_EQUIPE INT,
    CONSTRAINT FK_FUNCIONARIOS_VOO FOREIGN KEY (FUNC_EQUIPE) REFERENCES FUNCIONARIOS(ID_FUNC),
    CONSTRAINT FK_VOOS_EQUIPE FOREIGN KEY (VOO_EQUIPE) REFERENCES VOOS(ID_VOOS)
);



